#Word Embedding Tech using Embeding Layer in KEras

In [1]:
#used tensorflow >2.0 and Keras

In [10]:
pip install tensorflow

In [11]:
import tensorflow as tf
print(tf.__version__)

2.18.0


One Hot Encoding

In [12]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
## sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [14]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [15]:
### Vocabulary size
voc_size=500

#One Hot Representation"

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[92, 403, 295, 350], [92, 403, 295, 372], [92, 212, 295, 487], [301, 327, 27, 487, 424], [301, 327, 27, 487, 323], [111, 92, 220, 295, 139], [351, 161, 258, 487]]


for each word i will be having index number will be represneting in 1 AND 0 WILL BE VISIBLE 1

#Word Embedding Represntation

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [18]:
import numpy as np

#pading

In [19]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  92 403 295 350]
 [  0   0   0   0  92 403 295 372]
 [  0   0   0   0  92 212 295 487]
 [  0   0   0 301 327  27 487 424]
 [  0   0   0 301 327  27 487 323]
 [  0   0   0 111  92 220 295 139]
 [  0   0   0   0 351 161 258 487]]


Zeros will get added

In [20]:
## 10 feature dimesnions
dim=10


In [23]:
# model=Sequential()
# model.add(Embedding(voc_size,10,input_length=sent_length))
# model.compile('adam','mse')


from keras.models import Sequential
from keras.layers import Embedding

# Define your model
model = Sequential()

# Add the Embedding layer without input_length
model.add(Embedding(input_dim=voc_size, output_dim=10, input_shape=(sent_length,)))

# Compile the model
model.compile(optimizer='adam', loss='mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 8, 10)               │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  92, 403, 295, 350], dtype=int32)

In [28]:
# Reshape the input for prediction
input_data = np.expand_dims(embedded_docs[0], axis=0)  # For a single sample
# input_data = embedded_docs  # For the entire dataset

# Make predictions
predictions = model.predict(input_data)

print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step
[[[ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501
   -0.02062717  0.04292579  0.04756952 -0.01831806 -0.02993758]
  [ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501
   -0.02062717  0.04292579  0.04756952 -0.01831806 -0.02993758]
  [ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501
   -0.02062717  0.04292579  0.04756952 -0.01831806 -0.02993758]
  [ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501
   -0.02062717  0.04292579  0.04756952 -0.01831806 -0.02993758]
  [ 0.00812495  0.04177072 -0.02894865 -0.02590597 -0.03849349
   -0.04595038 -0.02607348  0.00255649 -0.03169061 -0.02461059]
  [ 0.02247384 -0.03657117  0.04836503  0.00557498  0.02922395
   -0.02016803  0.00303533  0.04065808 -0.02931255 -0.00246736]
  [-0.01878225 -0.0138834   0.01852414 -0.02121666 -0.00952798
    0.01300484 -0.04551562 -0.01378888 -0.01077571 -0.03755225]
  [ 0.03321061  0.02693105 -0.03632448  0.02304468  0.02674022
    0.042

In [31]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
[[[ 2.7048025e-02  2.4851885e-02 -3.3533461e-03  4.8392031e-02
   -4.2745005e-02 -2.0627165e-02  4.2925786e-02  4.7569517e-02
   -1.8318057e-02 -2.9937578e-02]
  [ 2.7048025e-02  2.4851885e-02 -3.3533461e-03  4.8392031e-02
   -4.2745005e-02 -2.0627165e-02  4.2925786e-02  4.7569517e-02
   -1.8318057e-02 -2.9937578e-02]
  [ 2.7048025e-02  2.4851885e-02 -3.3533461e-03  4.8392031e-02
   -4.2745005e-02 -2.0627165e-02  4.2925786e-02  4.7569517e-02
   -1.8318057e-02 -2.9937578e-02]
  [ 2.7048025e-02  2.4851885e-02 -3.3533461e-03  4.8392031e-02
   -4.2745005e-02 -2.0627165e-02  4.2925786e-02  4.7569517e-02
   -1.8318057e-02 -2.9937578e-02]
  [ 8.1249475e-03  4.1770723e-02 -2.8948653e-02 -2.5905967e-02
   -3.8493492e-02 -4.5950379e-02 -2.6073480e-02  2.5564916e-03
   -3.1690612e-02 -2.4610592e-02]
  [ 2.2473838e-02 -3.6571167e-02  4.8365030e-02  5.5749789e-03
    2.9223952e-02 -2.0168031e-02  3.0353293e-03  4.0658083e-02
   -2.9312551e-02 -2.4673566e-03]
 

In [32]:
embedded_docs[0]

array([  0,   0,   0,   0,  92, 403, 295, 350], dtype=int32)

In [33]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501 -0.02062717
   0.04292579  0.04756952 -0.01831806 -0.02993758]
 [ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501 -0.02062717
   0.04292579  0.04756952 -0.01831806 -0.02993758]
 [ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501 -0.02062717
   0.04292579  0.04756952 -0.01831806 -0.02993758]
 [ 0.02704803  0.02485188 -0.00335335  0.04839203 -0.04274501 -0.02062717
   0.04292579  0.04756952 -0.01831806 -0.02993758]
 [ 0.00812495  0.04177072 -0.02894865 -0.02590597 -0.03849349 -0.04595038
  -0.02607348  0.00255649 -0.03169061 -0.02461059]
 [ 0.02247384 -0.03657117  0.04836503  0.00557498  0.02922395 -0.02016803
   0.00303533  0.04065808 -0.02931255 -0.00246736]
 [-0.01878225 -0.0138834   0.01852414 -0.02121666 -0.00952798  0.01300484
  -0.04551562 -0.01378888 -0.01077571 -0.03755225]
 [ 0.03321061  0.02693105 -0.03632448  0.02304468  0.02674022  0.04240197
   0.02963612